#!/bin/bash

# location of peak files
inputDir=peak_files
# location of input to the script - output of HOMER mergePeaks
mergedFile=mergePeaks_output/test_101
# output file generated by mergePeaks_resolve
outFile=output/test_101_output.txt

MRES=../bin/x86_64/mergePeaks_resolve
time $MRES -m $mergedFile -i $inputDir -o $outFile


