# tests for script

curr=`pwd`;

MRES=../bin/x86_64/mergePeaks_resolve
# location of peak files
inputDir=../example/peak_files
# location of input to the script - output of HOMER mergePeaks
mergedFile=../example/mergePeaks_output/test_101
# output file generated by mergePeaks_resolve
outFile=../example/output/test_101_output.txt

cd ..
make clean
make
cd $curr;

# I/O args test
echo ""
echo "-----------------------------------"
echo "TEST 1 : No input args"
$MRES;

echo ""
echo "-----------------------------------"
echo "TEST 2 : No output file"
$MRES -m $mergedFile -i $inputDir

echo ""
echo "-----------------------------------"
echo "TEST 3: No input dir"
$MRES -m $mergedFile -o $outFile

echo ""
echo "-----------------------------------"
echo "TEST 4: No merged File"
$MRES -i $inputDir -o $outFile

echo "Tests done";

